services:

  backend:
    build:
      context: ./backend
    container_name: printcheck-backend

    expose:
      - "8000"

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
    container_name: printcheck-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped
